/*****************************************************************************
 *
 * Copyright (C) 2016-2024 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 */

#ifndef _APCB_V3_TOKEN_UID_H_
#define _APCB_V3_TOKEN_UID_H_
//
// @APCB_START
//

//
// @APCB_TOKEN
//

// =================================================================================================
// CBS CMN APCB Tokens (BOOLEAN)
// -------------------------------------------------------------------------------------------------
/** BOOLEAN_TRUE_FALSE_VALIDVAL
*   Value range for boolean type with True and False usage
*/
typedef enum {
  _FALSE = 0,      ///< False
  _TRUE = 1,       ///< True
} BOOLEAN_TRUE_FALSE_VALIDVAL;

/** BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
*   Value range for boolean type with Enable and Disable usage
*/
typedef enum {
  BOOLEAN_ENABLE_1_DISABLE_0_DISABLE = 0,      ///< Disable
  BOOLEAN_ENABLE_1_DISABLE_0_ENABLE = 1,       ///< Enable
} BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL;

/** BOOLEAN_ENABLE_0_DISABLE_1_VALIDVAL
*   Value range for boolean type with Enable and Disable usage
*/
typedef enum {
  BOOLEAN_ENABLE_0_DISABLE_1_DISABLE = 1,      ///< Disable
  BOOLEAN_ENABLE_0_DISABLE_1_ENABLE = 0,       ///< Enable
} BOOLEAN_ENABLE_0_DISABLE_1_VALIDVAL;

/** BOOLEAN_DISABLE_0_AUTO_VALIDVAL
*   Value range for boolean type with Disable and Auto usage
*/
typedef enum {
  BOOLEAN_DISABLE_0_AUTO_VALIDVAL_DISABLED = 0,///<Disabled
  BOOLEAN_DISABLE_0_AUTO_VALIDVAL_AUTO = 0xFF, ///<Auto
} BOOLEAN_DISABLE_0_AUTO_VALIDVAL;

/** BOOLEAN_ENABLE_1_AUTO_VALIDVAL
*   Value range for boolean type with Enable and Auto usage
*/
typedef enum {
  BOOLEAN_ENABLE_1_AUTO_VALIDVAL_DISABLED = 0,///<Enabled
  BOOLEAN_ENABLE_1_AUTO_VALIDVAL_AUTO = 0xFF, ///<Auto
} BOOLEAN_ENABLE_1_AUTO_VALIDVAL;

// -------------------------------------------------------------------------------------------------
/// @GROUPID: APCB_GROUP_TOKEN
/// @TYPEID: APCB_TYPE_TOKEN_BOOLEAN
/// @DATATYPE: BOOLEAN
/// @SIZE: 1

/// @DESC: PSP TP Port control
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_PSP_TP_PORT                                        0x0460ABE8  // bool

/// @DESC: PSP_ERROR_DISPLAY
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_PSP_ERROR_DISPLAY                                  0xDC33FF21  // bool

/// @DESC: PSP_EVENT_LOG_DISPLAY
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_PSP_EVENT_LOG_DISPLAY                              0x0C473E1C  // bool

/// @DESC: PSP_STOP_ON_ERROR
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_PSP_STOP_ON_ERROR                                  0xE7024A21  // bool

/// @DESC: MEMHOLEREMAPPING
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMHOLEREMAPPING                                   0x6A133AC5  // bool

/// @DESC: LIMITMEMORYTOBELOW1TB
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_LIMITMEMORYTOBELOW1TB                              0x5E71E6D8  // bool

/// @DESC: ENABLECHIPSELECTINTLV
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLECHIPSELECTINTLV                              0x6F81A115  // bool

/// @DESC: ENABLECHANNELINTLV
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLECHANNELINTLV                                 0x48254F73  // bool

/// @DESC: ENABLEECCFEATURE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEECCFEATURE                                   0xFA35F040  // bool

/// @DESC: ENABLEPOWERDOWN
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEPOWERDOWN                                    0xBBB185A2  // bool

/// @DESC: ENABLEPARITY
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEPARITY                                       0x3CB8CBD2  // bool

/// @DESC: ENABLEBANKSWIZZLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEBANKSWIZZLE                                  0x6414D160  // bool

/// @DESC: ENABLEMEMCLR
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEMEMCLR                                       0xC6ACDB37  // bool

/// @DESC: MEMRESTORECTL
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMRESTORECTL                                      0xFEDB01F8  // bool

/// @DESC: ISCAPSULEMODE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ISCAPSULEMODE                                      0x96176308  // bool

/// @DESC: AMPENABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_AMPENABLE                                          0x592CB3CA  // bool

/// @DESC: DRAMDOUBLEREFRESHRATE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATE                              0x44D40026  // bool

/// @DESC: ECCREDIRECTION
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ECCREDIRECTION                                     0xDEDE0E09  // bool

/// @DESC: ECCSYNCFLOOD
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ECCSYNCFLOOD                                       0x88BD40C2  // bool

/// @DESC: DQSTRAININGCONTROL
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DQSTRAININGCONTROL                                 0x3CAAA3FA  // bool

/// @DESC: UMAABOVE4G
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_UMAABOVE4G                                         0x77E41D2A  // bool

/// @DESC: MEMORYALLCLOCKSON
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYALLCLOCKSON                                  0xB95E0555  // bool

/// @DESC: IGNORESPDCHECKSUM
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_IGNORESPDCHECKSUM                                  0x7D369DBC  // bool

/// @DESC: MEMORYMODEUNGANGED
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYMODEUNGANGED                                 0x03CE1180  // bool

/// @DESC: MEMORYQUADRANKCAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYQUADRANKCAPABLE                              0xE6DFD3DC  // bool

/// @DESC: MEMORYRDIMMCAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYRDIMMCAPABLE                                 0x81726666  // bool

/// @DESC: MEMORYLRDIMMCAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYLRDIMMCAPABLE                                0x014FBF20  // bool

/// @DESC: MEMORYUDIMMCAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYUDIMMCAPABLE                                 0x3CF8A8EC  // bool

/// @DESC: MEMORYSODIMMCAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEMORYSODIMMCAPABLE                                0x7C61C187  // bool

/// @DESC: DIMMTYPEDDDR3CAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DIMMTYPEDDDR3CAPABLE                               0x0789210C  // bool

/// @DESC: DIMMTYPELPDDDR3CAPABLE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DIMMTYPELPDDDR3CAPABLE                             0xAD96AA30  // bool

/// @DESC: ENABLEBANKGROUPSWAP
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEBANKGROUPSWAP                                0x46920968  // bool

/// @DESC: ODTSCMDTHROTEN
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ODTSCMDTHROTEN                                     0xC0736395  // bool

/// @DESC: SWCMDTHROTEN
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_SWCMDTHROTEN                                       0xA29C1CF9  // bool

/// @DESC: FORCEPWRDOWNTHROTEN
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_FORCEPWRDOWNTHROTEN                                0x10849D6C  // bool

/// @DESC: ENABLEMEMPSTATE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEMEMPSTATE                                    0x56B93947  // bool

/// @DESC: DDRROUTEBALANCEDTEE
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DDRROUTEBALANCEDTEE                                0xE68C363D  // bool

/// @DESC: MEM_TEMP_CONTROLLED_REFRESH_EN
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_TEMP_CONTROLLED_REFRESH_EN                     0xF051E1C4  // bool

/// @DESC: ENABLEBANKGROUPSWAPALT
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ENABLEBANKGROUPSWAPALT                             0xA89D1BE8  // bool

/// @DESC: UECC_RETRY_DDR4
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_UECC_RETRY_DDR4                                    0xBFF00125  // bool

/// @DESC: MEM_MBIST_AGGR_STATIC_LANE_CTRL
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_CTRL                    0x77E6F2C9  // bool

/// @DESC: DRAMDOUBLEREFRESHRATEEN
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATEEN                            0x974E8E7C  // unused

/// @DESC: CBS_CMN_MEM_CTRLLER_DRAM_ECC_EN_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DRAM_ECC_EN_DDR4               0x9C6D6993  // bool

/// @DESC: POST_PACKAGE_REPAIR_ENABLE
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_POST_PACKAGE_REPAIR_ENABLE                         0xCDC03E4E  // bool

/// @DESC: MEM_MBIST_TGT_STATIC_LANE_CTRL
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_CTRL                     0xE1CC135E  // bool

/// @DESC: CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4
/// @RANGE: BOOLEAN_DISABLE_0_AUTO_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4           0x77A2B63A  // bool in code, uint8 in x86 data //bool

/// @DESC: CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4           0x229EDFE4  // bool in code, uint8 in x86 data //bool

/// @DESC: CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4                 0x0EF08D04  // bool in code, uint8 in x86 data //bool

/// @DESC: CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4                   0xA01AB8A0  // bool in code, uint8 in x86 data //bool

/// @DESC: CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4             0x8D3AB10E  // bool in code, uint8 in x86 data //bool

/// @DESC: CBS_CMN_MEM_MBIST_EN
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_EN                               0x0D0AE86F  // uint8 //bool

/// @DESC: CBS_CMN_MEM_UECC_RETRY_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_UECC_RETRY_DDR4                        0x42216E4B  // Duplicate with APCB_TOKEN_UID_UECC_RETRY_DDR4 //bool

/// @DESC: CBS_CMN_MEM_DATA_POISONING_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_POISONING_DDR4                    0x598E8661  // uint8 in x86 data, not used in code //bool

/// @DESC: CBS_CMN_MEM_OVERCLOCK_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_AUTO_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_DDR4                         0x593292BE  // uint8 in x86 data, parent control in code //bool

/// @DESC: CBS_CMN_MEM_ADDRESS_HASH_RM_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_AUTO_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_RM_DDR4                   0x50A6D6CA  // bool

/// @DESC: CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4             0x6301BD18  // bool

/// @DESC: CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4                    0x68444D72  // bool

/// @DESC: CBS_CMN_MEM_MBIST_AGGRESSORS
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_AGGRESSORS                       0xD98B8639  // bool

/// @DESC: CBS_CMN_MEM_MBIST_PER_BIT_SECONDARY_DIE_REPORT
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_PER_BIT_SECONDARY_DIE_REPORT         0xF4943BAD  // bool

/// @DESC: CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4                 0x2D3BB9D8  // bool

/// @DESC: CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_ALT_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_ALT_DDR4       0xAE6507DA  // bool

/// @DESC: DF_PROBE_FILTER_ENABLE
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_DF_PROBE_FILTER                                    0x6597C573  // uint8

/// @DESC: PSP_ENABLE_DEBUG_MODE
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_PSP_ENABLE_DEBUG_MODE                              0xD1091CD0  // uint8

/// @DESC: MEM_CTRLLER_WR_CRC_EN_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_WR_CRC_EN_DDR4                 0x94451A4B  // bool

/// @DESC: MEM_DIS_MEM_ERR_INJ
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_DIS_MEM_ERR_INJ                        0xFF756025  // bool

/// @DESC: MEM_RCD_PARITY_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_RCD_PARITY_DDR4                        0x7E23FE78  // bool

/// @DESC: MEM_WRITE_CRC_RETRY_DDR4
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_WRITE_CRC_RETRY_DDR4                   0x25FB6EA6  // bool

/// @DESC: MEM_EARLY_PAGE_ACTIVATE_DDR4
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_CBS_DBG_MEM_EARLY_PAGE_ACTIVATE_DDR4               0x3D1FB3FF  // bool, debug items

/// @DESC: CCX PPIN opt-in
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_CCX_PPIN_OPT_IN                                    0x6A6700FD  // bool

/// @DESC: Group D platform selection
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_GROUP_D_PLATFORM                                   0x68318493  // bool

/// @DESC: Force Data Mask Disable
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_FORCE_DATA_MASK_DISABLE_DDR4                   0xD68482B3  //bool

/// @DESC: Mother board TYPE 0
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MOTHERBOARD_TYPE_0                                 0x0536464B

/// @DESC: DisRefCmdThrotCnt
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DISREFCMDTHROTCNT                                  0x8F84DCB4

/// @DESC: OdtsEn
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_ODTSEN                                             0xAEB3F914

/// @DESC: Forces to enable OC mode which will disable FCLK DPM and Memory Pstates
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_GNB_FCLK_OC_FLAG                                   0x8A109D3F

/// @DESC: MEM VDDIO control
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_OC_VDDIO_CONTROL                               0x6CD36DBE

/// @DESC: Discard OC condition and enforce to enable MEM VDDIO adjustment
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_OC_VDDIO_CONTROL_ENFORCE_ON                    0x72958E2C

/// @DESC: Enable LN2 mode
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_GNB_SMU_LN2_MODE                                   0x359597F5

/// @DESC: MCTP reroute enable
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MCTP_REROUTE_ENABLE                                0x79F2A8D5  // bool

/// @DESC: DRAM Latency Enhance
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_DRAM_LATENCY_ENHANCE                           0x1D0A5E46

// =================================================================================================
// CBS CMN APCB Tokens (1BYTE)
// -------------------------------------------------------------------------------------------------
/** ENABLE_DISABLE_AUTO_OPTION
*   Value range for UINT8 type with Enable, Disable and Auto usage
*/
typedef enum {
  ENABLE_DISABLE_AUTO_OPTION_DISABLED = 0, ///<Disabled
  ENABLE_DISABLE_AUTO_OPTION_ENABLED = 1,  ///<Enabled
  ENABLE_DISABLE_AUTO_OPTION_AUTO = 3,     ///<Auto
} ENABLE_DISABLE_AUTO_OPTION;

/** MANUAL_AUTO_0X00_VALIDVAL
*   Value range for UINT8 type with AUTO: 0x00 and ENABLE: 0x01 usage
*/
typedef enum {
  MANUAL_AUTO_0X00_VALIDVAL_AUTO = 0x00,      ///< AUTO
  MANUAL_AUTO_0X00_VALIDVAL_MANUAL = 1,       ///< MANUAL
} MANUAL_AUTO_0X00_VALIDVAL;

/** MANUAL_AUTO_0XFF_VALIDVAL
*   Value range for UINT8 type with AUTO: 0xFF and ENABLE: 0x01 usage
*/
typedef enum {
  MANUAL_AUTO_0XFF_VALIDVAL_AUTO = 0xFF,      ///< AUTO
  MANUAL_AUTO_0XFF_VALIDVAL_MANUAL = 1,       ///< MANUAL
} MANUAL_AUTO_0XFF_VALIDVAL;

// -------------------------------------------------------------------------------------------------
/// @GROUPID: APCB_GROUP_TOKEN
/// @TYPEID: APCB_TYPE_TOKEN_1BYTE
/// @DATATYPE: UINT8
/// @SIZE: 1

/// @DESC: CCX_CPB
  #define APCB_TOKEN_UID_CCX_CPB                                            0x9DA294C2

/// @DESC: CCX_SEV_ASID_COUNT
/// @RANGE: CPU_SEV_ASID_COUNT_VALIDVAL
  #define APCB_TOKEN_UID_CCX_SEV_ASID_COUNT                                 0x55876720  //uint8
/** CPU_SEV_ASID_COUNT_VALIDVAL
*   Value range for APCB_TOKEN_UID_CCX_SEV_ASID_COUNT
*/
typedef enum {
  CPU_SEV_ASID_COUNT_253ASIDS = 0,///<253 ASIDs
  CPU_SEV_ASID_COUNT_509ASIDS = 1,///<509 ASIDs
  CPU_SEV_ASID_COUNT_AUTO = 3,     ///<Auto
} CPU_SEV_ASID_COUNT_VALIDVAL;

/// @DESC: XTRIG7_WORKAROUND
/// @RANGE: CPU_XTRIG7_WORKAROUND_VALIDVAL
  #define APCB_TOKEN_UID_XTRIG7_WORKAROUND                                  0x2762E77B  //uint8
/** CPU_XTRIG7_WORKAROUND_VALIDVAL
*   Value range for APCB_TOKEN_UID_XTRIG7_WORKAROUND
*/
typedef enum {
  CPU_XTRIG7_WORKAROUND_AUTO = 0xFF,         ///<Auto
  CPU_XTRIG7_WORKAROUND_NOWORKAROUND = 0,    ///<No Workaround
  CPU_XTRIG7_WORKAROUND_BRONZEWORKAROUND = 1,///<Bronze Workaround
} CPU_XTRIG7_WORKAROUND_VALIDVAL;

/// @DESC: MEM_MBIST_AGGRESSORS_CHNL
/// @RANGE: MEM_MBIST_AGGRESSORS_CHNL_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_AGGRESSORS_CHNL                          0xDCD1444A  //uint8
/** MEM_MBIST_AGGRESSORS_CHNL_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_AGGRESSORS_CHNL
*/
typedef enum {
  MEM_MBIST_AGGRESSORS_CHNL_DISABLED = 0,          ///<Disabled
  MEM_MBIST_AGGRESSORS_CHNL_1AGGRESSORCHANNEL = 1, ///<1 Aggressor Channel
  MEM_MBIST_AGGRESSORS_CHNL_3AGGRESSORCHANNELS = 3,///<3 Aggressor Channels
  MEM_MBIST_AGGRESSORS_CHNL_7AGGRESSORCHANNELS = 7,///<7 Aggressor Channels
} MEM_MBIST_AGGRESSORS_CHNL_VALIDVAL;

/// @DESC: MEM_MBIST_PATTERN_LENGTH
/// @RANGE: 0~12 = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_PATTERN_LENGTH                           0xAE7BAEDD  //uint8

/// @DESC: MEM_MBIST_PATTERN_SELECT
/// @RANGE: MEM_MBIST_PATTERN_SELECT_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_PATTERN_SELECT                           0xF527EBF8  //uint8
/** MEM_MBIST_PATTERN_SELECT_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_PATTERN_SELECT
*/
typedef enum {
  MEM_MBIST_PATTERN_SELECT_PRBS = 0,///<PRBS
  MEM_MBIST_PATTERN_SELECT_SSO = 1, ///<SSO
  MEM_MBIST_PATTERN_SELECT_BOTH = 2,///<Both
} MEM_MBIST_PATTERN_SELECT_VALIDVAL;

/// @DESC: MEM_MBIST_AGGR_STATIC_LANE_SEL_ECC
/// @RANGE: 0x00~0x0A = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL_ECC                 0x57122E99  //uint8

/// @DESC: MEM_MBIST_AGGR_STATIC_LANE_VAL
/// @RANGE: 0x00~0x0A = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_VAL                     0x4474D416  //uint8

/// @DESC: MEM_MBIST_TGT_STATIC_LANE_SEL_ECC
/// @RANGE: 0x00~0x0A = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL_ECC                  0xA6E92CEE  //uint8

/// @DESC: MEM_MBIST_TGT_STATIC_LANE_VAL
/// @RANGE: 0x00~0x0A = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_VAL                      0x4D7E0206  //uint8

/// @DESC: MEM_MBIST_DATA_EYE_TYPE
/// @RANGE: MEM_MBIST_DATA_EYE_TYPE_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_DATA_EYE_TYPE                            0x4E2EDC1B  //uint8
/** MEM_MBIST_DATA_EYE_TYPE_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_DATA_EYE_TYPE
*/
typedef enum {
  MEM_MBIST_DATA_EYE_TYPE_1DVOLTAGESWEEP = 0,     ///<1D Voltage Sweep
  MEM_MBIST_DATA_EYE_TYPE_1DTIMINGSWEEP = 1,      ///<1D Timing Sweep
  MEM_MBIST_DATA_EYE_TYPE_2DFULLDATAEYE = 2,      ///<2D Full Data Eye
  MEM_MBIST_DATA_EYE_TYPE_WORSTCASEMARGINONLY = 3,///<Worst Case Margin Only
} MEM_MBIST_DATA_EYE_TYPE_VALIDVAL;

/// @DESC: MEM_MBIST_WORST_CASE_GRAN
/// @RANGE: MEM_MBIST_WORST_CASE_GRAN_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_WORST_CASE_GRAN                          0x23B0B6A1  //uint8
/** MEM_MBIST_WORST_CASE_GRAN_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_WORST_CASE_GRAN
*/
typedef enum {
  MEM_MBIST_WORST_CASE_GRAN_PERCHIPSELECT = 0,///<Per Chip Select
  MEM_MBIST_WORST_CASE_GRAN_PERNIBBLE = 1,    ///<Per Nibble
} MEM_MBIST_WORST_CASE_GRAN_VALIDVAL;

/// @DESC: MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP
/// @RANGE: MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP               0x35D6A4F8  //uint8
/** MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP
*/
typedef enum {
  MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_1 = 0,///<1
  MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_2 = 1,///<2
  MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_4 = 4,///<4
} MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_VALIDVAL;

/// @DESC: MEM_MBIST_READ_DATA_EYE_TIMING_STEP
/// @RANGE: MEM_MBIST_READ_DATA_EYE_TIMING_STEP_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_TIMING_STEP                0x58CCD28A  //uint8
/** MEM_MBIST_READ_DATA_EYE_TIMING_STEP_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_TIMING_STEP
*/
typedef enum {
  MEM_MBIST_READ_DATA_EYE_TIMING_STEP_1 = 1,///<1
  MEM_MBIST_READ_DATA_EYE_TIMING_STEP_2 = 2,///<2
  MEM_MBIST_READ_DATA_EYE_TIMING_STEP_4 = 4,///<4
} MEM_MBIST_READ_DATA_EYE_TIMING_STEP_VALIDVAL;

/// @DESC: MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP
/// @RANGE: MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP              0xCDA61022  //uint8
/** MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP
*/
typedef enum {
  MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_1 = 0,///<1
  MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_2 = 1,///<2
  MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_4 = 4,///<4
} MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_VALIDVAL;

/// @DESC: MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP
/// @RANGE: MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_VALIDVAL
  #define APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP               0xD9025142  //uint8
/** MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_VALIDVAL
*   Value range for APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP
*/
typedef enum {
  MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_1 = 1,///<1
  MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_2 = 2,///<2
  MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_4 = 4,///<4
} MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_VALIDVAL;

/// @DESC: _DF_SYNC_FLOOD_PROP
/// @RANGE: DF_SYNC_FLOOD_PROP_VALIDVAL
  #define APCB_TOKEN_UID_DF_SYNC_FLOOD_PROP                                 0x49639134  //uint8

/// @DESC: _DF_EXT_IP_SYNC_FLOOD_PROP
/// @RANGE: DF_EXT_IP_SYNC_FLOOD_PROP_VALIDVAL
  #define APCB_TOKEN_UID_DF_EXT_IP_SYNC_FLOOD_PROP                          0xFFFE0B07  //uint8

/** DF_SYNC_FLOOD_PROP_VALIDVAL
*   Value range for APCB_TOKEN_UID_DF_SYNC_FLOOD_PROP
*/
typedef enum {
  DF_SYNC_FLOOD_PROP_SYNCFLOODDISABLED = 1,///<Sync flood disabled
  DF_SYNC_FLOOD_PROP_SYNCFLOODENABLED = 0, ///<Sync flood enabled
  DF_SYNC_FLOOD_PROP_AUTO = 0xFF,          ///<Auto
} DF_SYNC_FLOOD_PROP_VALIDVAL;

/// @DESC: DF_GMI_ENCRYPT
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_DF_GMI_ENCRYPT                                     0x08A45920  // uint8 //uint8

/// @DESC: DF_XGMI_ENCRYPT
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_DF_XGMI_ENCRYPT                                    0x6BD32F1C  // uint8 //uint8

/// @DESC: DF_SAVE_RESTORE_MEM_ENCRYPT
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_DF_SAVE_RESTORE_MEM_ENCRYPT                        0x7B3D1F75  // uint8 //uint8

/// @DESC: DF_BOTTOMIO
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_DF_BOTTOMIO                                        0x8FB98529  // uint8

/// @DESC: Select BMC Gen Speed
/// @RANGE: BMC_LINK_SPEED
  #define APCB_TOKEN_UID_BMC_LINK_SPEED                                     0x9C790F4B  // uint8

typedef enum {
  TP_BYTE_PRINT_AUTO     = 0xFF,   ///< Auto
  TP_BYTE_PRINT_DISABLE  = 0,      ///< Disable
  TP_BYTE_PRINT_ENABLE   = 1,      ///< Enable
} TP_BYTE_PRINT_VALIDVAL;
/// @DESC: TP_BYTE_PRINT
/// @RANGE: TP_BYTE_PRINT_VALIDVAL
  #define APCB_TOKEN_UID_TP_BYTE_PRINT                                      0xF77493CC
/** BMC_LINK_SPEED
*   Value range for APCB_TOKEN_UID_BMC_LINK_SPEED
*/
typedef enum {
  PCIE_GEN1_SPEED = 1,    ///< PCIE Gen1 Speed
  PCIE_GEN2_SPEED = 2,    ///< PCIE Gen2 Speed
} BMC_LINK_SPEED;

/// @DESC: FCH_CONSOLE_OUT_ENABLE
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_FCH_CONSOLE_OUT_ENABLE                             0xDDB759DA  // uint8

  /// @DESC: CONSOLE_OUT_BOOT_MODE
  /// @RANGE: 0~0xFF = UITN8 Valid Range
  /// BIT[0]  - Normal boot
  /// BIT[1]  - S3/S0i3
  #define APCB_TOKEN_UID_CONSOLE_OUT_BOOT_MODE                              0x4B993A83  // uint833

/// @DESC: ABL Serial Baud Rate
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_ABL_SERIAL_BAUD_RATE                               0xAE46CEA4  // uint8

/// @DESC: Data Fabric Memory Interleaving Control
/// @RANGE: DF_MEM_INTERLEAVING_VALIDVAL
  #define APCB_TOKEN_UID_DF_MEM_INTERLEAVING                                0xCE0176EF  // uint8 //uint8
/** DF_MEM_INTERLEAVING_VALIDVAL
*  Value range for APCB_TOKEN_UID_DF_MEM_INTERLEAVING
*/
typedef enum {
  DF_MEM_INTLV_NONE     = 0,      ///< No interleave
  DF_MEM_INTLV_CHANNEL  = 1,      ///< Channel interleave
  DF_MEM_INTLV_DIE      = 2,      ///< Die interleave
  DF_MEM_INTLV_SOCKET   = 3,      ///< Socket interleave
  DF_MEM_INTLV_AUTO     = 7,      ///< Auto interleave
} DF_MEM_INTERLEAVING_VALIDVAL;

/// @DESC: Data Fabric DRAM Interleave Size
/// @RANGE: DF_MEM_INTLV_SIZE_VALIDVAL
  #define APCB_TOKEN_UID_DF_MEM_INTERLEAVING_SIZE                           0x2606C42E  //uint8
/** DF_MEM_INTLV_SIZE_VALIDVAL
*  Value range for APCB_TOKEN_UID_DF_MEM_INTERLEAVING_SIZE
*/
typedef enum {
  DF_MEM_INTLV_SIZE_256BYTES = 0,  ///< Interleave size 256 bytes
  DF_MEM_INTLV_SIZE_512BYTES = 1,  ///< Interleave size 512 bytes
  DF_MEM_INTLV_SIZE_1KB = 2,       ///< Interleave size 1024 bytes
  DF_MEM_INTLV_SIZE_2KB = 3,       ///< Interleave size 2048 bytes
  DF_MEM_INTLV_SIZE_AUTO = 7,      ///< Auto
} DF_MEM_INTLV_SIZE_VALIDVAL;

typedef enum {
  DF_DRAM_INTLV_SIZE_256 = 0,     ///< Interleave size 256 bytes
  DF_DRAM_INTLV_SIZE_512 = 1,     ///< Interleave size 512 bytes
  DF_DRAM_INTLV_SIZE_1024 = 2,    ///< Interleave size 1024 bytes
  DF_DRAM_INTLV_SIZE_2048 = 3,    ///< Interleave size 2048 bytes
} DF_DRAM_INTLV_SIZE_VAL;


/// @DESC: DISPLAY_PMU_TRAIN_RESULTS
/// @RANGE: BOOLEAN_TRUE_FALSE_VALIDVAL
  #define APCB_TOKEN_UID_DISPLAY_PMU_TRAIN_RESULTS                          0x9E36A9D4  // boolean

/// @DESC: DF_REMAP_AT_1TB
/// @RANGE: DF_REMAP_AT_1TB_VALIDVAL
  #define APCB_TOKEN_UID_DF_REMAP_AT_1TB                                    0x35EE96F3  // uint8
/* DF_REMAP_AT_1TB_VALIDVAL
 *  Value range for APCB_TOKEN_UID_DF_REMAP_AT_1TB_VALUE
 */
typedef enum {
  DF_REMAP_AT_1TB_FALSE = 0,    ///< Memory under the 1TB IOMMU 'hole' is lost
  DF_REMAP_AT_1TB_TRUE,         ///< Memory under the 1TB IOMMU 'hole' is remapped to above 1TB boundary
  DF_REMAP_AT_1TB_AUTO = 0xFF   ///< Auto
} DF_REMAP_AT_1TB_VALIDVAL;

/// @DESC: FCH_SMBUS_SPEED
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_FCH_SMBUS_SPEED                                    0x24473329

/// @DESC: MEM_TRAINING_HDTCTRL
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_TRAINING_HDTCTRL                               0xAF6D3A6F

/// @DESC: MEM_RESTORE_VALID_DAYS
/// @RANGE: 0~0xFFFFFFFF = UINT32 Valid Range
  #define APCB_TOKEN_UID_MEM_RESTORE_VALID_DAYS                             0x6BD70482

/// @DESC: CBS_CMN_MEM_SPEED_DDR4
/// @RANGE: MEM_SPEED_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_SPEED_DDR4                             0xE0604CE9  // uint8 //uint8
/** MEM_SPEED_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_SPEED_DDR4
*/
typedef enum {
  MEM_SPEED_DDR4_AUTO = 0xFF,///<Auto
  MEM_SPEED_DDR4_667MHZ = 0x14,///<667MHz
  MEM_SPEED_DDR4_800MHZ = 0x18,///<800MHz
  MEM_SPEED_DDR4_933MHZ = 0x1C,///<933MHz
  MEM_SPEED_DDR4_1067MHZ = 0x20,///<1067MHz
  MEM_SPEED_DDR4_1200MHZ = 0x24,///<1200MHz
  MEM_SPEED_DDR4_1333MHZ = 0x28,///<1333MHz
  MEM_SPEED_DDR4_1400MHZ = 0x2A,///<1400MHz
  MEM_SPEED_DDR4_1467MHZ = 0x2C,///<1467MHz
  MEM_SPEED_DDR4_1533MHZ = 0x2E,///<1533MHz
  MEM_SPEED_DDR4_1600MHZ = 0x30,///<1600MHz
  MEM_SPEED_DDR4_1667MHZ = 0x32,///<1667MHz
  MEM_SPEED_DDR4_1733MHZ = 0x34,///<1733MHz
  MEM_SPEED_DDR4_1800MHZ = 0x36,///<1800MHz
  MEM_SPEED_DDR4_1867MHZ = 0x38,///<1867MHz
  MEM_SPEED_DDR4_1933MHZ = 0x3A,///<1933MHz
  MEM_SPEED_DDR4_2000MHZ = 0x3C,///<2000MHz
  MEM_SPEED_DDR4_333MHZ = 4,///<333MHz
  MEM_SPEED_DDR4_400MHZ = 6,///<400MHz
  MEM_SPEED_DDR4_533MHZ = 0xA,///<533MHz
  MEM_SPEED_DDR4_1050MHZ = 0x19,///<1050MHz
  MEM_SPEED_DDR4_1066MHZ = 0x1A,///<1066MHz
} MEM_SPEED_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TCL_DDR4
/// @RANGE: MEM_TIMING_TCL_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCL_DDR4                        0xB2D12C4E  // uint8 //uint8
/** MEM_TIMING_TCL_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCL_DDR4
*/
typedef enum {
  MEM_TIMING_TCL_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TCL_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TCL_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TCL_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TCL_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TCL_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TCL_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TCL_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TCL_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TCL_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TCL_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TCL_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TCL_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TCL_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TCL_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TCL_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TCL_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TCL_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TCL_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TCL_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TCL_DDR4_1BHCLK = 0x1B,///<1Bh Clk
  MEM_TIMING_TCL_DDR4_1CHCLK = 0x1C,///<1Ch Clk
  MEM_TIMING_TCL_DDR4_1DHCLK = 0x1D,///<1Dh Clk
  MEM_TIMING_TCL_DDR4_1EHCLK = 0x1E,///<1Eh Clk
  MEM_TIMING_TCL_DDR4_1FHCLK = 0x1F,///<1Fh Clk
  MEM_TIMING_TCL_DDR4_20HCLK = 0x20,///<20h Clk
  MEM_TIMING_TCL_DDR4_21HCLK = 0x21,///<21h Clk
} MEM_TIMING_TCL_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRCDRD_DDR4
/// @RANGE: MEM_TIMING_TRCDRD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDRD_DDR4                     0xB22E12F7  // uint8 //uint8
/** MEM_TIMING_TRCDRD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDRD_DDR4
*/
typedef enum {
  MEM_TIMING_TRCDRD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRCDRD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRCDRD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRCDRD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRCDRD_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRCDRD_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRCDRD_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TRCDRD_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TRCDRD_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TRCDRD_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TRCDRD_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TRCDRD_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TRCDRD_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TRCDRD_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TRCDRD_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TRCDRD_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TRCDRD_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TRCDRD_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TRCDRD_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TRCDRD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRCDRD_DDR4_1BHCLK = 0x1B,///<1Bh Clk
} MEM_TIMING_TRCDRD_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRCDWR_DDR4
/// @RANGE: MEM_TIMING_TRCDWR_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDWR_DDR4                     0xB3840F07  // uint8 //uint8
/** MEM_TIMING_TRCDWR_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDWR_DDR4
*/
typedef enum {
  MEM_TIMING_TRCDWR_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRCDWR_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRCDWR_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRCDWR_DDR4_0XACLK = 0xA,///<0xA Clk
  MEM_TIMING_TRCDWR_DDR4_0XBCLK = 0xB,///<0xB Clk
  MEM_TIMING_TRCDWR_DDR4_0XCCLK = 0xC,///<0xC Clk
  MEM_TIMING_TRCDWR_DDR4_0XDCLK = 0xD,///<0xD Clk
  MEM_TIMING_TRCDWR_DDR4_0XECLK = 0xE,///<0xE Clk
  MEM_TIMING_TRCDWR_DDR4_0XFCLK = 0xF,///<0xF Clk
  MEM_TIMING_TRCDWR_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TRCDWR_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TRCDWR_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TRCDWR_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TRCDWR_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TRCDWR_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TRCDWR_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TRCDWR_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TRCDWR_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TRCDWR_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TRCDWR_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TRCDWR_DDR4_1BHCLK = 0x1B,///<1Bh Clk
} MEM_TIMING_TRCDWR_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRP_DDR4
/// @RANGE: MEM_TIMING_TRP_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRP_DDR4                        0xA2D655C8  // uint8 //uint8
/** MEM_TIMING_TRP_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRP_DDR4
*/
typedef enum {
  MEM_TIMING_TRP_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRP_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRP_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRP_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRP_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRP_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRP_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TRP_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TRP_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TRP_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TRP_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TRP_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TRP_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRP_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TRP_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TRP_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TRP_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TRP_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TRP_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TRP_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TRP_DDR4_1BHCLK = 0x1B,///<1Bh Clk
} MEM_TIMING_TRP_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRAS_DDR4
/// @RANGE: MEM_TIMING_TRAS_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRAS_DDR4                       0x03E98A84  // uint8 //uint8
/** MEM_TIMING_TRAS_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRAS_DDR4
*/
typedef enum {
  MEM_TIMING_TRAS_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TRAS_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TRAS_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TRAS_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TRAS_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TRAS_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TRAS_DDR4_1BHCLK = 0x1B,///<1Bh Clk
  MEM_TIMING_TRAS_DDR4_1CHCLK = 0x1C,///<1Ch Clk
  MEM_TIMING_TRAS_DDR4_1DHCLK = 0x1D,///<1Dh Clk
  MEM_TIMING_TRAS_DDR4_1EHCLK = 0x1E,///<1Eh Clk
  MEM_TIMING_TRAS_DDR4_1FHCLK = 0x1F,///<1Fh Clk
  MEM_TIMING_TRAS_DDR4_20HCLK = 0x20,///<20h Clk
  MEM_TIMING_TRAS_DDR4_21HCLK = 0x21,///<21h Clk
  MEM_TIMING_TRAS_DDR4_22HCLK = 0x22,///<22h Clk
  MEM_TIMING_TRAS_DDR4_23HCLK = 0x23,///<23h Clk
  MEM_TIMING_TRAS_DDR4_24HCLK = 0x24,///<24h Clk
  MEM_TIMING_TRAS_DDR4_25HCLK = 0x25,///<25h Clk
  MEM_TIMING_TRAS_DDR4_26HCLK = 0x26,///<26h Clk
  MEM_TIMING_TRAS_DDR4_27HCLK = 0x27,///<27h Clk
  MEM_TIMING_TRAS_DDR4_28HCLK = 0x28,///<28h Clk
  MEM_TIMING_TRAS_DDR4_29HCLK = 0x29,///<29h Clk
  MEM_TIMING_TRAS_DDR4_2AHCLK = 0x2A,///<2Ah Clk
  MEM_TIMING_TRAS_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRAS_DDR4_2BHCLK = 0x2B,///<2Bh Clk
  MEM_TIMING_TRAS_DDR4_2CHCLK = 0x2C,///<2Ch Clk
  MEM_TIMING_TRAS_DDR4_2DHCLK = 0x2D,///<2Dh Clk
  MEM_TIMING_TRAS_DDR4_2EHCLK = 0x2E,///<2Eh Clk
  MEM_TIMING_TRAS_DDR4_2FHCLK = 0x2F,///<2Fh Clk
  MEM_TIMING_TRAS_DDR4_30HCLK = 0x30,///<30h Clk
  MEM_TIMING_TRAS_DDR4_31HCLK = 0x31,///<31h Clk
  MEM_TIMING_TRAS_DDR4_32HCLK = 0x32,///<32h Clk
  MEM_TIMING_TRAS_DDR4_33HCLK = 0x33,///<33h Clk
  MEM_TIMING_TRAS_DDR4_34HCLK = 0x34,///<34h Clk
  MEM_TIMING_TRAS_DDR4_35HCLK = 0x35,///<35h Clk
  MEM_TIMING_TRAS_DDR4_36HCLK = 0x36,///<36h Clk
  MEM_TIMING_TRAS_DDR4_37HCLK = 0x37,///<37h Clk
  MEM_TIMING_TRAS_DDR4_38HCLK = 0x38,///<38h Clk
  MEM_TIMING_TRAS_DDR4_39HCLK = 0x39,///<39h Clk
  MEM_TIMING_TRAS_DDR4_3AHCLK = 0x3A,///<3Ah Clk
} MEM_TIMING_TRAS_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4                   0xBBC7849A  // uint8 in x86 data, not used in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRC_DDR4
/// @RANGE: 0x1D~0x87 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_DDR4                        0x5B082A2B  // uint8 in data //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRRD_S_DDR4
/// @RANGE: MEM_TIMING_TRRD_S_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_S_DDR4                     0x50B2D463  // uint8 //uint8
/** MEM_TIMING_TRRD_S_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_S_DDR4
*/
typedef enum {
  MEM_TIMING_TRRD_S_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRRD_S_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRRD_S_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRRD_S_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRRD_S_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRRD_S_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRRD_S_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRRD_S_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRRD_S_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRRD_S_DDR4_0CHCLK = 0xC,///<0Ch Clk
} MEM_TIMING_TRRD_S_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRRD_L_DDR4
/// @RANGE: MEM_TIMING_TRRD_L_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_L_DDR4                     0xFC23535E  // uint8 //uint8
/** MEM_TIMING_TRRD_L_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_L_DDR4
*/
typedef enum {
  MEM_TIMING_TRRD_L_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRRD_L_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRRD_L_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRRD_L_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRRD_L_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRRD_L_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRRD_L_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRRD_L_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRRD_L_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRRD_L_DDR4_0CHCLK = 0xC,///<0Ch Clk
} MEM_TIMING_TRRD_L_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4                  0xB36B7473  // uint8 in x86 data, used as 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TFAW_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_DDR4                       0xDE1D6178  // uint8 //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TWTR_S_DDR4
/// @RANGE: MEM_TIMING_TWTR_S_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_S_DDR4                     0xEB6A9FE9  // uint8 //uint8
/** MEM_TIMING_TWTR_S_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_S_DDR4
*/
typedef enum {
  MEM_TIMING_TWTR_S_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWTR_S_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWTR_S_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWTR_S_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWTR_S_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWTR_S_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWTR_S_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWTR_S_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWTR_S_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWTR_S_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWTR_S_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWTR_S_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TWTR_S_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TWTR_S_DDR4_0EHCLK = 0xE,///<0Eh Clk
} MEM_TIMING_TWTR_S_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TWTR_L_DDR4
/// @RANGE: MEM_TIMING_TWTR_L_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_L_DDR4                     0x5782D479  // uint8 //uint8
/** MEM_TIMING_TWTR_L_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_L_DDR4
*/
typedef enum {
  MEM_TIMING_TWTR_L_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWTR_L_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWTR_L_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWTR_L_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWTR_L_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWTR_L_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWTR_L_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWTR_L_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWTR_L_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWTR_L_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWTR_L_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWTR_L_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TWTR_L_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TWTR_L_DDR4_0EHCLK = 0xE,///<0Eh Clk
} MEM_TIMING_TWTR_L_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4                   0x5C26F15B  // uint8 //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TWR_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_DDR4                        0x4FC9F17E  // uint8 //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4               0x2BC2CA69  // uint8 //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRCPAGE_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4                    0x1A82F1F6  // uint8 (new data), uint16 (old data in x86), uint8 in code. //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4            0xC71A49AA  // uint8 in x86 data, 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4
/// @RANGE: 0x01~0x0F = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4                 0x6A594A63  // uint8 //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4            0x91371469  // uint8 , 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4
/// @RANGE: 0x01~0x3F = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4                 0xA148AB5F  // uint8 in x86 data, uint32 varible in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4                  0x86ED48B5  // uint8 , 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4                 0x6D8E4884  // uint8 , 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4                 0xFBB240FD  // uint8 , 2nd level parent control in code //uint8

/// @DESC: CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4
/// @RANGE: MEM_CTRLLER_PROC_ODT_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4                  0xE74CFD9B  // uint8 //uint8
/** MEM_CTRLLER_PROC_ODT_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4
*/
typedef enum {
  MEM_CTRLLER_PROC_ODT_DDR4_AUTO = 0xFF,///<Auto
  MEM_CTRLLER_PROC_ODT_DDR4_HIGHIMPEDANCE = 0,///<High Impedance
  MEM_CTRLLER_PROC_ODT_DDR4_480OHM = 1,///<480 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_240OHM = 2,///<240 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_160OHM = 3,///<160 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_120OHM = 8,///<120 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_96OHM = 9,///<96 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_80OHM = 10,///<80 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_686OHM = 11,///<68.6 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_60OHM = 0x18,///<60 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_533OHM = 0x19,///<53.3 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_48OHM = 0x1A,///<48 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_436OHM = 0x1B,///<43.6 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_40OHM = 0x38,///<40 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_369OHM = 0x39,///<36.9 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_343OHM = 0x3A,///<34.3 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_32OHM = 0x3B,///<32 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_30OHM = 0x3E,///<30 ohm
  MEM_CTRLLER_PROC_ODT_DDR4_282OHM = 0x3F,///<28.2 ohm
} MEM_CTRLLER_PROC_ODT_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_MBIST_TESTMODE
/// @RANGE: MEM_MBIST_TESTMODE_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_TESTMODE                         0x4D0C053F  //uint8
/** MEM_MBIST_TESTMODE_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_TESTMODE
*/
typedef enum {
  MEM_MBIST_TESTMODE_INTERFACEMODE = 0,///<Interface Mode
  MEM_MBIST_TESTMODE_DATAEYEMODE = 1,///<Data Eye Mode
} MEM_MBIST_TESTMODE_VALIDVAL;

/// @DESC: DF_MEM_CLEAR
/// @RANGE: ENABLE_DISABLE_AUTO_OPTION
  #define APCB_TOKEN_UID_DF_MEM_CLEAR                                       0x9D177E57  // uint8 in code, uint8 and bool in data //uint8

/// @DESC: CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4
/// @RANGE: MEM_TIMING_TRDRD_SC_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4                   0x2E199CAA  //uint8
/** MEM_TIMING_TRDRD_SC_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4
*/
typedef enum {
  MEM_TIMING_TRDRD_SC_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TRDRD_SC_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TRDRD_SC_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TRDRD_SC_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRDRD_SC_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRDRD_SC_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRDRD_SC_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRDRD_SC_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRDRD_SC_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRDRD_SC_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRDRD_SC_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRDRD_SC_DDR4_AUTO = 0xFF,///<Auto
} MEM_TIMING_TRDRD_SC_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4
/// @RANGE: MEM_TIMING_TRDRD_SD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4                   0x6AD7647F  //uint8
/** MEM_TIMING_TRDRD_SD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4
*/
typedef enum {
  MEM_TIMING_TRDRD_SD_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TRDRD_SD_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TRDRD_SD_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRDRD_SD_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRDRD_SD_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRDRD_SD_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRDRD_SD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRDRD_SD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRDRD_SD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRDRD_SD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRDRD_SD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRDRD_SD_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TRDRD_SD_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRDRD_SD_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRDRD_SD_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TRDRD_SD_DDR4_0FHCLK = 0xF,///<0Fh Clk
} MEM_TIMING_TRDRD_SD_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4
/// @RANGE: MEM_TIMING_TRDRD_DD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4                   0xA1E46AFC  //uint8
/** MEM_TIMING_TRDRD_DD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4
*/
typedef enum {
  MEM_TIMING_TRDRD_DD_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TRDRD_DD_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TRDRD_DD_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRDRD_DD_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRDRD_DD_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRDRD_DD_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRDRD_DD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRDRD_DD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRDRD_DD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRDRD_DD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRDRD_DD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRDRD_DD_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TRDRD_DD_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRDRD_DD_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRDRD_DD_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TRDRD_DD_DDR4_0FHCLK = 0xF,///<0Fh Clk
} MEM_TIMING_TRDRD_DD_DDR4;

/// @DESC: CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4
/// @RANGE: MEM_TIMING_TWRWR_SC_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4                   0x4DE9DD1F  //uint8
/** MEM_TIMING_TWRWR_SC_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4
*/
typedef enum {
  MEM_TIMING_TWRWR_SC_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TWRWR_SC_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWRWR_SC_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWRWR_SC_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWRWR_SC_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWRWR_SC_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWRWR_SC_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWRWR_SC_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWRWR_SC_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWRWR_SC_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWRWR_SC_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWRWR_SC_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWRWR_SC_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TWRWR_SC_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TWRWR_SC_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TWRWR_SC_DDR4_0FHCLK = 0xF,///<0Fh Clk
} MEM_TIMING_TWRWR_SC_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4
/// @RANGE: MEM_TIMING_TWRWR_SD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4                   0xA95E4B3B  //uint8
/** MEM_TIMING_TWRWR_SD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4
*/
typedef enum {
  MEM_TIMING_TWRWR_SD_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWRWR_SD_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWRWR_SD_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWRWR_SD_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWRWR_SD_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWRWR_SD_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWRWR_SD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWRWR_SD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWRWR_SD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWRWR_SD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWRWR_SD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWRWR_SD_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TWRWR_SD_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TWRWR_SD_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TWRWR_SD_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TWRWR_SD_DDR4_0FHCLK = 0xF,///<0Fh Clk
} MEM_TIMING_TWRWR_SD_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4
/// @RANGE: MEM_TIMING_TWRWR_DD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4                   0x9E720EC8  //uint8
/** MEM_TIMING_TWRWR_DD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4
*/
typedef enum {
  MEM_TIMING_TWRWR_DD_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWRWR_DD_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWRWR_DD_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWRWR_DD_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWRWR_DD_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWRWR_DD_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWRWR_DD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWRWR_DD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWRWR_DD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWRWR_DD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWRWR_DD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWRWR_DD_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TWRWR_DD_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TWRWR_DD_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TWRWR_DD_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TWRWR_DD_DDR4_0FHCLK = 0xF,///<0Fh Clk
} MEM_TIMING_TWRWR_DD_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRDWR_DDR4
/// @RANGE: MEM_TIMING_TRDWR_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDWR_DDR4                      0x7636900E  //uint8
/** MEM_TIMING_TRDWR_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDWR_DDR4
*/
typedef enum {
  MEM_TIMING_TRDWR_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TRDWR_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TRDWR_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TRDWR_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TRDWR_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TRDWR_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TRDWR_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRDWR_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRDWR_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRDWR_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRDWR_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRDWR_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRDWR_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TRDWR_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TRDWR_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TRDWR_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TRDWR_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TRDWR_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TRDWR_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TRDWR_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TRDWR_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TRDWR_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TRDWR_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TRDWR_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TRDWR_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TRDWR_DDR4_1BHCLK = 0x1B,///<1Bh Clk
  MEM_TIMING_TRDWR_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRDWR_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TRDWR_DDR4_1CHCLK = 0x1C,///<1Ch Clk
  MEM_TIMING_TRDWR_DDR4_1DHCLK = 0x1D,///<1Dh Clk
  MEM_TIMING_TRDWR_DDR4_1EHCLK = 0x1E,///<1Eh Clk
  MEM_TIMING_TRDWR_DDR4_1FHCLK = 0x1F,///<1Fh Clk
} MEM_TIMING_TRDWR_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TWRRD_DDR4
/// @RANGE: MEM_TIMING_TWRRD_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRRD_DDR4                      0x8FD5A3D2  //uint8
/** MEM_TIMING_TWRRD_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRRD_DDR4
*/
typedef enum {
  MEM_TIMING_TWRRD_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TWRRD_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TWRRD_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TWRRD_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TWRRD_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TWRRD_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TWRRD_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TWRRD_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TWRRD_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TWRRD_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TWRRD_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TWRRD_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TWRRD_DDR4_0CH = 0xC,///<0Ch
  MEM_TIMING_TWRRD_DDR4_0DH = 0xD,///<0Dh
  MEM_TIMING_TWRRD_DDR4_0EH = 0xE,///<0Eh
  MEM_TIMING_TWRRD_DDR4_0FH = 0xF,///<0Fh
} MEM_TIMING_TWRRD_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TRTP_DDR4
/// @RANGE: MEM_TIMING_TRTP_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRTP_DDR4                       0x88B9F33B  //uint8
/** MEM_TIMING_TRTP_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRTP_DDR4
*/
typedef enum {
  MEM_TIMING_TRTP_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TRTP_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TRTP_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TRTP_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TRTP_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TRTP_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TRTP_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TRTP_DDR4_5CLK = 0x5,///<5 Clk
  MEM_TIMING_TRTP_DDR4_6CLK = 0x6,///<6 Clk
  MEM_TIMING_TRTP_DDR4_7CLK = 0x7,///<7 Clk
  MEM_TIMING_TRTP_DDR4_0EHCLK = 0xE,///<0Eh Clk
} MEM_TIMING_TRTP_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TCWL_DDR4
/// @RANGE: MEM_TIMING_TCWL_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCWL_DDR4                       0xBDBA463D  //uint8
/** MEM_TIMING_TCWL_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCWL_DDR4
*/
typedef enum {
  MEM_TIMING_TCWL_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TCWL_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TCWL_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TCWL_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TCWL_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TCWL_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TCWL_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TCWL_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TCWL_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TCWL_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TCWL_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TCWL_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TCWL_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TCWL_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TCWL_DDR4_16HCLK = 0x16,///<16h Clk
} MEM_TIMING_TCWL_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4
/// @RANGE: MANUAL_AUTO_0XFF_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4               0x9CC11046  //uint8

/// @DESC: CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4
/// @RANGE: MEM_CTRLLER_RTT_NOM_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4                   0xBFFF404B  //uint8
/** MEM_CTRLLER_RTT_NOM_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4
*/
typedef enum {
  MEM_CTRLLER_RTT_NOM_DDR4_RTT_NOMDISABLE = 0,///<Rtt_Nom Disable
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ4 = 1,///<RZQ/4
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ2 = 2,///<RZQ/2
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ6 = 3,///<RZQ/6
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ1 = 4,///<RZQ/1
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ5 = 5,///<RZQ/5
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ3 = 6,///<RZQ/3
  MEM_CTRLLER_RTT_NOM_DDR4_RZQ7 = 7,///<RZQ/7
  MEM_CTRLLER_RTT_NOM_DDR4_AUTO = 0xFF,///<Auto
} MEM_CTRLLER_RTT_NOM_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4
/// @RANGE: MEM_CTRLLER_RTT_WR_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4                    0xA80353D7  //uint8
/** MEM_CTRLLER_RTT_WR_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4
*/
typedef enum {
  MEM_CTRLLER_RTT_WR_DDR4_DYNAMICODTOFF = 0,///<Dynamic ODT Off
  MEM_CTRLLER_RTT_WR_DDR4_RZQ2 = 1,///<RZQ/2
  MEM_CTRLLER_RTT_WR_DDR4_RZQ1 = 2,///<RZQ/1
  MEM_CTRLLER_RTT_WR_DDR4_HIZ = 3,///<Hi-Z
  MEM_CTRLLER_RTT_WR_DDR4_RZQ3 = 4,///<RZQ/3
  MEM_CTRLLER_RTT_WR_DDR4_AUTO = 0xFF,///<Auto
} MEM_CTRLLER_RTT_WR_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4
/// @RANGE: MEM_CTRLLER_RTT_PARK_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4                  0x58BF5D3E  //uint8
/** MEM_CTRLLER_RTT_PARK_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4
*/
typedef enum {
  MEM_CTRLLER_RTT_PARK_DDR4_RTT_PARKDISABLE = 0,///<Rtt_PARK Disable
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ4 = 1,///<RZQ/4
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ2 = 2,///<RZQ/2
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ6 = 3,///<RZQ/6
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ1 = 4,///<RZQ/1
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ5 = 5,///<RZQ/5
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ3 = 6,///<RZQ/3
  MEM_CTRLLER_RTT_PARK_DDR4_RZQ7 = 7,///<RZQ/7
  MEM_CTRLLER_RTT_PARK_DDR4_AUTO = 0xFF,///<Auto
} MEM_CTRLLER_RTT_PARK_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_TIMING_TCKE_DDR4
/// @RANGE: MEM_TIMING_TCKE_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCKE_DDR4                       0x5EF92FB0  //uint8
/** MEM_TIMING_TCKE_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCKE_DDR4
*/
typedef enum {
  MEM_TIMING_TCKE_DDR4_AUTO = 0xFF,///<Auto
  MEM_TIMING_TCKE_DDR4_1CLK = 1,///<1 Clk
  MEM_TIMING_TCKE_DDR4_2CLK = 2,///<2 Clk
  MEM_TIMING_TCKE_DDR4_3CLK = 3,///<3 Clk
  MEM_TIMING_TCKE_DDR4_4CLK = 4,///<4 Clk
  MEM_TIMING_TCKE_DDR4_5CLK = 5,///<5 Clk
  MEM_TIMING_TCKE_DDR4_6CLK = 6,///<6 Clk
  MEM_TIMING_TCKE_DDR4_7CLK = 7,///<7 Clk
  MEM_TIMING_TCKE_DDR4_8CLK = 8,///<8 Clk
  MEM_TIMING_TCKE_DDR4_9CLK = 9,///<9 Clk
  MEM_TIMING_TCKE_DDR4_0AHCLK = 0xA,///<0Ah Clk
  MEM_TIMING_TCKE_DDR4_0BHCLK = 0xB,///<0Bh Clk
  MEM_TIMING_TCKE_DDR4_0CHCLK = 0xC,///<0Ch Clk
  MEM_TIMING_TCKE_DDR4_0DHCLK = 0xD,///<0Dh Clk
  MEM_TIMING_TCKE_DDR4_0EHCLK = 0xE,///<0Eh Clk
  MEM_TIMING_TCKE_DDR4_0FHCLK = 0xF,///<0Fh Clk
  MEM_TIMING_TCKE_DDR4_10HCLK = 0x10,///<10h Clk
  MEM_TIMING_TCKE_DDR4_11HCLK = 0x11,///<11h Clk
  MEM_TIMING_TCKE_DDR4_12HCLK = 0x12,///<12h Clk
  MEM_TIMING_TCKE_DDR4_13HCLK = 0x13,///<13h Clk
  MEM_TIMING_TCKE_DDR4_14HCLK = 0x14,///<14h Clk
  MEM_TIMING_TCKE_DDR4_15HCLK = 0x15,///<15h Clk
  MEM_TIMING_TCKE_DDR4_16HCLK = 0x16,///<16h Clk
  MEM_TIMING_TCKE_DDR4_17HCLK = 0x17,///<17h Clk
  MEM_TIMING_TCKE_DDR4_18HCLK = 0x18,///<18h Clk
  MEM_TIMING_TCKE_DDR4_19HCLK = 0x19,///<19h Clk
  MEM_TIMING_TCKE_DDR4_1AHCLK = 0x1A,///<1Ah Clk
  MEM_TIMING_TCKE_DDR4_1BHCLK = 0x1B,///<1Bh Clk
  MEM_TIMING_TCKE_DDR4_1CHCLK = 0x1C,///<1Ch Clk
  MEM_TIMING_TCKE_DDR4_1DHCLK = 0x1D,///<1Dh Clk
  MEM_TIMING_TCKE_DDR4_1EHCLK = 0x1E,///<1Eh Clk
  MEM_TIMING_TCKE_DDR4_1FHCLK = 0x1F,///<1Fh Clk
} MEM_TIMING_TCKE_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_CLDO_VDDP_CTL
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_CLDO_VDDP_CTL                              0xE033C709  //uint8

/// @DESC: CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4
/// @RANGE: MEM_CTRLLER2_T_MODE_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4                   0x0677966C  //uint8
/** MEM_CTRLLER2_T_MODE_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4
*/
typedef enum {
  MEM_CTRLLER2_T_MODE_DDR4_1T = 0,///<1T
  MEM_CTRLLER2_T_MODE_DDR4_2T = 1,///<2T
  MEM_CTRLLER2_T_MODE_DDR4_AUTO = 0xFF,///<Auto
} MEM_CTRLLER2_T_MODE_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CAD_BUS_TIMING_CTL_DDR4
/// @RANGE: MANUAL_AUTO_0XFF_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_TIMING_CTL_DDR4                0x264B7625  //uint8

/// @DESC: CBS_CMN_MEM_ADDR_CMD_SETUP_DDR4
/// @RANGE: 0x00~0x3F = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_SETUP_DDR4                    0x1E974F51  //uint8

/// @DESC: CBS_CMN_MEM_CS_ODT_SETUP_DDR4
/// @RANGE: 0x00~0x3F = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CS_ODT_SETUP_DDR4                      0x3B1B99E9  //uint8

/// @DESC: CBS_CMN_MEM_CKE_SETUP_DDR4
/// @RANGE: 0x00~0x3F = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CKE_SETUP_DDR4                         0x37D13B99  //uint8

/// @DESC: CBS_CMN_MEM_CAD_BUS_DRV_STREN_CTL_DDR4
/// @RANGE: MANUAL_AUTO_0XFF_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_DRV_STREN_CTL_DDR4             0xDB047BEB  //uint8

/// @DESC: CBS_CMN_MEM_CAD_BUS_CLK_DRV_STREN_DDR4
/// @RANGE: MEM_CAD_BUS_CLK_DRV_STREN_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CLK_DRV_STREN_DDR4             0xD8ADC426  //uint8
/** MEM_CAD_BUS_CLK_DRV_STREN_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CLK_DRV_STREN_DDR4
*/
typedef enum {
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_AUTO = 0xFF,///<Auto
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_1200OHM = 0,///<120.0 Ohm
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_600OHM = 1,///<60.0 Ohm
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_400OHM = 3,///<40.0 Ohm
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_300OHM = 7,///<30.0 Ohm
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_240OHM = 15,///<24.0 Ohm
  MEM_CAD_BUS_CLK_DRV_STREN_DDR4_200OHM = 31,///<20.0 Ohm
} MEM_CAD_BUS_CLK_DRV_STREN_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4
/// @RANGE: MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4        0xF91E8072  //uint8
/** MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4
*/
typedef enum {
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_AUTO = 0xFF,///<Auto
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_1200OHM = 0,///<120.0 Ohm
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_600OHM = 1,///<60.0 Ohm
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_400OHM = 3,///<40.0 Ohm
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_300OHM = 7,///<30.0 Ohm
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_240OHM = 15,///<24.0 Ohm
  MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_200OHM = 31,///<20.0 Ohm
} MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4
/// @RANGE: MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4          0x7BBE9AF1  //uint8
/** MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4
*/
typedef enum {
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_AUTO = 0xFF,///<Auto
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_1200OHM = 0,///<120.0 Ohm
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_600OHM = 1,///<60.0 Ohm
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_400OHM = 3,///<40.0 Ohm
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_300OHM = 7,///<30.0 Ohm
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_240OHM = 15,///<24.0 Ohm
  MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_200OHM = 31,///<20.0 Ohm
} MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4_VALIDVAL;

/// @DESC: CBS_CMN_MEM_CAD_BUS_CKE_DRV_STREN_DDR4
/// @RANGE: MEM_CAD_BUS_CKE_DRV_STREN_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CKE_DRV_STREN_DDR4             0x1014364F  //uint8
/** MEM_CAD_BUS_CKE_DRV_STREN_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CKE_DRV_STREN_DDR4
*/
typedef enum {
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_AUTO = 0xFF,///<Auto
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_1200OHM = 0,///<120.0 Ohm
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_600OHM = 1,///<60.0 Ohm
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_400OHM = 3,///<40.0 Ohm
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_300OHM = 7,///<30.0 Ohm
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_240OHM = 15,///<24.0 Ohm
  MEM_CAD_BUS_CKE_DRV_STREN_DDR4_200OHM = 31,///<20.0 Ohm
} MEM_CAD_BUS_CKE_DRV_STREN_DDR4_VALIDVAL;

typedef enum {
  MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4_X4 = 0,///<x4
  MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4_X8 = 1,///<x8
  MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4_X16 = 2,///<x16
  MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4_AUTO = 0xFF,///<Auto
} MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4_VALIDVAL;

/// @DESC: MEM_TSME_ENABLE
/// @RANGE: BOOLEAN_ENABLE_1_DISABLE_0_VALIDVAL
  #define APCB_TOKEN_UID_MEM_TSME_ENABLE                                    0xD1FA6660  // bool

/// @DESC: MEM_ADDR_CMD_PARITY_ERROR_MAX_REPLAY_D
/// @RANGE: 0x00~0x3F = UINT8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_PARITY_ERROR_MAX_REPLAY_DDR4  0x04E6A482

/// @DESC: MEM_ADDR_CMD_PARITY_RETRY_DDR4
/// @RANGE: MEM_ADDR_CMD_PARITY_RETRY_DDR4_VALIDVAL
  #define APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_PARITY_RETRY_DDR4             0xBE8BEBCE
/** MEM_ADDR_CMD_PARITY_RETRY_DDR4_VALIDVAL
*   Value range for APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_PARITY_RETRY_DDR4
*/
typedef enum {
  MEM_ADDR_CMD_PARITY_RETRY_DDR4_AUTO = 0xFF,///<Auto
  MEM_ADDR_CMD_PARITY_RETRY_DDR4_DISABLED = 0,///<Disabled
  MEM_ADDR_CMD_PARITY_RETRY_DDR4_ENABLED = 1,///<Enabled
} MEM_ADDR_CMD_PARITY_RETRY_DDR4_VALIDVAL;

/// @DESC: MEM_WRITE_CRC_ERROR_MAX_REPLAY_DDR4
/// @RANGE: 0x01~0x08 = UINT8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_WRITE_CRC_ERROR_MAX_REPLAY_DDR4        0x74A08BEC  //uint8

/// @DESC: CPU_SYNC_FLOOD_ON_MCA
/// @RANGE: 0x00~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_CPU_SYNC_FLOOD_ON_MCA                              0x96664127

/// @DESC: xGMI Link Configuration
/// @RANGE: DF_XGMI_LINK_CFG_VALIDVAL
  #define APCB_TOKEN_UID_DF3_XGMI2_LINK_CFG                                 0xB0B6AD3E  // uint8
  #define   DF3_XGMI2_LINK_CFG_2LINK  0
  #define   DF3_XGMI2_LINK_CFG_3LINK  1
  #define   DF3_XGMI2_LINK_CFG_4LINK  2
/** DF_XGMI_LINK_CFG_VALIDVAL
*   Value range for APCB_TOKEN_UID_DF3_XGMI2_LINK_CFG
*/
typedef enum {
  DF_XGMI_LINK_CFG_AUTO = 3,///<Auto
  DF_XGMI_LINK_CFG_3XGMILINKS = 1,///<3 xGMI Links
  DF_XGMI_LINK_CFG_4XGMILINKS = 2,///<4 xGMI Links
} DF_XGMI_LINK_CFG_VALIDVAL;

/// @DESC: DF_3LINK_MAX_XGMI_SPEED
/// @RANGE: DF_XGMI_LINK_SPEED
  #define APCB_TOKEN_UID_DF_3LINK_MAX_XGMI_SPEED                            0x53BA449B  // uint8

/// @DESC: DF_4LINK_MAX_XGMI_SPEED
/// @RANGE: DF_XGMI_LINK_SPEED
  #define APCB_TOKEN_UID_DF_4LINK_MAX_XGMI_SPEED                            0x3F307CB3  // uint8
/* DF_XGMI_LINK_SPEED
 *  Value range for APCB_TOKEN_UID_DF_3LINK_MAX_XGMI_SPEED_VALUE
 *  Value range for APCB_TOKEN_UID_DF_4LINK_MAX_XGMI_SPEED_VALUE
 */
typedef enum {
  DF_XGMI_LINK_SPEED_640 = 0,       ///< 6.4 Gbps
  DF_XGMI_LINK_SPEED_746,           ///< 7.467 Gbps
  DF_XGMI_LINK_SPEED_853,           ///< 8.533 Gbps
  DF_XGMI_LINK_SPEED_960,           ///< 9.6 Gbps
  DF_XGMI_LINK_SPEED_1066,          ///< 10.667 Gbps
  DF_XGMI_LINK_SPEED_1100,          ///< 11 Gbps
  DF_XGMI_LINK_SPEED_1200,          ///< 12 Gbps
  DF_XGMI_LINK_SPEED_1300,          ///< 13 Gbps
  DF_XGMI_LINK_SPEED_1400,          ///< 14 Gbps
  DF_XGMI_LINK_SPEED_1500,          ///< 15 Gbps
  DF_XGMI_LINK_SPEED_1600,          ///< 16 Gbps
  DF_XGMI_LINK_SPEED_1700,          ///< 17 Gbps
  DF_XGMI_LINK_SPEED_1800,          ///< 18 Gbps
  DF_XGMI_LINK_SPEED_1900,          ///< 19 Gbps
  DF_XGMI_LINK_SPEED_2000,          ///< 20 Gbps
  DF_XGMI_LINK_SPEED_2100,          ///< 21 Gbps
  DF_XGMI_LINK_SPEED_2200,          ///< 22 Gbps
  DF_XGMI_LINK_SPEED_2300,          ///< 23 Gbps
  DF_XGMI_LINK_SPEED_2400,          ///< 24 Gbps
  DF_XGMI_LINK_SPEED_2500,          ///< 25 Gbps
  DF_XGMI_LINK_SPEED_AUTO = 0xFF    ///< Auto
} DF_XGMI_LINK_SPEED;

/// @DESC: DF_DRAM_NPS
/// @RANGE: DF_DRAM_NPS_VALIDVAL
  #define APCB_TOKEN_UID_DF_DRAM_NPS                                        0x2CF3DAC9  // uint8
/* DF_DRAM_NPS_VALIDVAL
 *  Value range for APCB_TOKEN_UID_DF_DRAM_NPS_VALUE
 */
typedef enum {
  DF_DRAM_NPS_0 = 0,      ///< No NUMA nodes
  DF_DRAM_NPS_1,          ///< 1 NUMA node per socket
  DF_DRAM_NPS_2,          ///< 2 NUMA node per socket
  DF_DRAM_NPS_4,          ///< 4 NUMA node per socket
  DF_DRAM_NPS_AUTO = 7    ///< Auto
} DF_DRAM_NPS_VALIDVAL;

/// @DESC: DF_INVERT_DRAM_MAP
/// @RANGE: 0x00~0xFF = UINT8 Valid Range
  #define APCB_TOKEN_UID_DF_INVERT_DRAM_MAP                                 0x6574B2C0  // uint8

/// @DESC: DF_SPF_WAY_CTRL
/// @RANGE: 0x00~0xFF = UINT8 Valid Range
  #define APCB_TOKEN_UID_DF_SPF_WAY_CTRL                                    0x71094904  // uint8

/// @DESC: PCIE_RESET_PIN_SELECT
/// @RANGE: 0x00~0x4 = UITN8 Valid Range
  #define APCB_TOKEN_UID_PCIE_RESET_PIN_SELECT                              0x8C0B2DE9  // uint8

/// @DESC: UCLK DIV1 MODE
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_UCLK_DIV1_MODE                     0xF0947E37  // uint8

/// @DESC: VDDCR_SOC_VID
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_VDDCR_SOC_VID                      0x4CAD640C  // uint8

/// @DESC: FCLK FREQUENCY
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_FCLK_FREQUENCY                     0xF1823F38  // uint8

/// @DESC: UCLK FREQUENCY
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_UCLK_FREQUENCY                     0x75C8500B  // uint8

/// @DESC: MEMCLK FREQUENCY
/// @RANGE: 0~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_MEMCLK_FREQUENCY                   0xA31DB44A  // uint8

/// @DESC: RCD F0RC0F nLadd (APCB override)
/// @RANGE: Auto, 0, 1, 2, 3, 4
  #define APCB_TOKEN_UID_MEM_TIMING_RCD_F0RC0F_NLADD_OVERRIDE               0xD155798A  // uint8

/// @DESC: RCD PARITY
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_RCD_PARITY                                         0x647D7662

/// @DESC: DRAM Address Command Parity Retry
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_DRAM_ADDRESS_COMMAND_PARITY_RETRY                  0x3E7C51F8

/// @DESC: Max Parity Error Replay
/// @RANGE: 0~0x3f = UITN8 Valid Range
  #define APCB_TOKEN_UID_MAX_PARITY_ERROR_REPLAY                            0xC9E9A1C9

/// @DESC: Write CRC enable
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_CTRLLER_WR_CRC                                 0x7D1C6E46

/// @DESC: DRAM Write CRC Enable and Retry Limit
/// @RANGE: 0~1 = UITN8 Valid Range
  #define APCB_TOKEN_UID_DRAM_WRITE_CRC_ENABLE_AND_RETRY_LIMIT              0xC73A7692

/// @DESC: Max Write CRC Error Replay
/// @RANGE: 0~0x3f = UITN8 Valid Range
  #define APCB_TOKEN_UID_MAX_WRITE_CRC_ERROR_REPLAY                         0x6BB1ACF9

/// @DESC: RollWindowDepth
/// @RANGE: 01~0xff = UITN8 Valid Range
  #define APCB_TOKEN_UID_ROLLWINDOWDEPTH                                    0x5985083A

/// @DESC: PMU Pattern Bits Control
/// @RANGE: MANUAL_AUTO_0X00_VALIDVAL
  #define APCB_TOKEN_UID_MEM_CTRLLER_PMU_PATTERN_BITS_CTRL_DDR4             0x46D97109  // uint8

/// @DESC: PMU Pattern Bits
/// @RANGE: 0~0xA = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_CTRLLER_PMU_PATTERN_BITS_DDR4                  0xC2FBEAFF  // uint8

/// @DESC: DF_PSTATE_MODE_SELECT
/// @RANGE: 0x00~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_DF_PSTATE_MODE_SELECT                              0xAEB84B12  // uint8
/** APCB_TOKEN_UID_DF_PSTATE_MODE_SELECT_VALIDVAL
*   Value range for APCB_TOKEN_UID_DF_PSTATE_MODE_SELECT
*/
typedef enum {
  GNB_SMU_DF_PSTATE_MODE_SELECT_NORMAL = 0,///<Normal
  GNB_SMU_DF_PSTATE_MODE_SELECT_LIMIT_HIGHEST = 1,///<Limit Highest
  GNB_SMU_DF_PSTATE_MODE_SELECT_LIMITALL = 2,///<Limit All
  GNB_SMU_DF_PSTATE_MODE_SELECT_AUTO = 0xFF,///<Auto
} GNB_SMU_DF_PSTATE_MODE_SELECT_VALIDVAL;

/// @DESC: DF_XGMI_TXEQ_MODE
/// @RANGE: DF_XGMI_TXEQ_MODE_VALIDVAL
  #define APCB_TOKEN_UID_DF_XGMI_TXEQ_MODE                                  0xADE79549  // uint8
/* DF_XGMI_TXEQ_MODE_VALIDVAL
 *  Value range for APCB_TOKEN_UID_DF_XGMI_TXEQ_MODE
 */
typedef enum {
  DF_XGMI_TXEQ_MODE_DISABLED = 0,
  DF_XGMI_TXEQ_MODE_ENABLED_BY_LANE,
  DF_XGMI_TXEQ_MODE_ENABLED_BY_LINK,
  DF_XGMI_TXEQ_MODE_ENABLED_BY_LINK_PLUS_RX_VETTING,
  DF_XGMI_TXEQ_MODE_AUTO = 0xFF
} DF_XGMI_TXEQ_MODE_VALIDVAL;

/// @DESC: The number of training failure/retries required before boot from recovery mode
/// @RANGE: 0~10 = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_OVERCLOCK_FAIL_CNT                             0xE5325C7B  //uint8

/// @DESC: MEM_CTRLLER_MR6_VREF_DQ_DDR4
/// @RANGE: 0x00~0x7F = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_CTRLLER_MR6_VREF_DQ_DDR4                       0x6649F4D1  // uint8

/// @DESC: MEM_CTRLLER_CPU_VREF_TRAINING_SEED_DDR
/// @RANGE: 0x00~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_MEM_CTRLLER_CPU_VREF_TRAINING_SEED_DDR4            0xC7389840  // uint8

/// @DESC: PSP_RPMC_ENABLE
/// @RANGE: 0x00~0xFF = UITN8 Valid Range
  #define APCB_TOKEN_UID_PSP_RPMC_ENABLE                                    0x4967F4FC  // uint8

/// @DESC: PSP_RPMC_RECOVERY_TYPE
/// @RANGE: 0x00~0xFF = UITN8 Valid Range
/// @details currently only 0 or 1 is acceptable
/// 0 : halt the system
/// 1 : set the recovery flag to notify BIOS
  #define APCB_TOKEN_UID_RPMC_RECOVERY_TYPE                                 0xCFEB85E2

/// @DESC: RX_DAT_CHN_DLY_DBG
/// @RANGE: 0~1 = UINT8 Valid Range
  #define APCB_TOKEN_UID_CBS_DBG_MEM_RX_DAT_CHN_DLY_DDR4                    0x1AB002CD  // uint8

/// @DESC: RX_DAT_CHN_DLY_CMN
/// @RANGE: 0~1 = UINT8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_RX_DAT_CHN_DLY_DDR4                    0x9D35337D  // uint8

/// @DESC: MEM_DFI_MRL_MARGIN_DDR4
/// @RANGE: 0~31 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_DFI_MRL_MARGIN_DDR4                    0x5687D670  // uint8

/// @DESC: MEM_TIMING_A_RD_PTR_MP0_DDR4
/// @RANGE: 0~15 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_A_RD_PTR_MP0_DDR4               0x44D5B1BE  // uint8

/// @DESC: MEM_TIMING_A_RD_PTR_MP1_DDR4
/// @RANGE: 0~127 = UITN8 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_A_RD_PTR_MP1_DDR4               0xF7CA85CC  // uint8

// =================================================================================================
// CBS CMN APCB Tokens (2BYTE)
// -------------------------------------------------------------------------------------------------
/// @GROUPID: APCB_GROUP_TOKEN
/// @TYPEID: APCB_TYPE_TOKEN_2BYTES
/// @DATATYPE: UINT16
/// @SIZE: 2

/// @DESC: CBS_CMN_MEM_TIMING_TRFC2_DDR4
/// @RANGE: 0x003C~0x03DE = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_DDR4                      0xEF6CF7B3  // uint16 //uint16

/// @DESC: CBS_CMN_MEM_TIMING_TRFC4_DDR4
/// @RANGE: 0x003C~0x03DE = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_DDR4                      0x4A05C5E2  // uint16 //uint16

/// @DESC: PSP_SYSHUB_WDT_INTERVAL
/// @RANGE: 0x0000~0xFFFF = UITN16 Valid Range
  #define APCB_TOKEN_UID_PSP_SYSHUB_WDT_INTERVAL                            0xEDB5E4C9  // uint16

/// @DESC: OVERCLOCK_VDDP_VOLTAGE
/// @RANGE: 0x0000~0x07FF = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_VDDP_VOLTAGE                       0xAB4BABF4  // uint16

/// @DESC: OVERCLOCK_VDDG_VOLTAGE
/// @RANGE: 0x0000~0x07FF = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_VDDG_VOLTAGE                       0xEE9F031C  // uint16

/// @DESC: OVERCLOCK_IOD_VDDG_VOLTAGE
/// @RANGE: 0x0000~0x07FF = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_IOD_VDDG_VOLTAGE                   0x93CA7EA3  // uint16

/// @DESC: OVERCLOCK_CCD_VDDG_VOLTAGE
/// @RANGE: 0x0000~0x07FF = UITN16 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_GNB_SMU_CCD_VDDG_VOLTAGE                   0xC286E57A  // uint16

/// @DESC: MEM_ADDRESS_HASH_BANK_2_COL_XOR
/// @RANGE: 0x0000~0x1FFF = UITN16 Valid Range
  #define APCB_TOKEN_UID_MEM_ADDRESS_HASH_BANK_2_COL_XOR                    0x7A2B20AE

// =================================================================================================
// CBS CMN APCB Tokens (4BYTE)
// -------------------------------------------------------------------------------------------------
/// @GROUPID: APCB_GROUP_TOKEN
/// @TYPEID: APCB_TYPE_TOKEN_4BYTES
/// @DATATYPE: UINT32
/// @SIZE: 4

/// @DESC: CCX_MIN_SEV_ASID
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_CCX_MIN_SEV_ASID                                   0xA7C33753  // uint32

/// @DESC: DF_PCI_MMIO_SIZE
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_DF_PCI_MMIO_SIZE                                   0x3D9B7D7B  // uint32

/// @DESC: DF_CAKE_CRC_THRESH_PERF_BOUNDS
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_DF_CAKE_CRC_THRESH_PERF_BOUNDS                     0x9258CF45  // uint32

/// @DESC: USERTIMINGMODE
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_USERTIMINGMODE                                     0xFC560D7D  // uint32

/// @DESC: MEMCLOCKVALUE
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_MEMCLOCKVALUE                                      0xCC83F65F  // uint32

/// @DESC: UMASIZE
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_UMASIZE                                            0x37B1F8CF  // uint32

/// @DESC: UMAALIGNMENT
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_UMAALIGNMENT                                       0x57DDF512  // uint32

/// @DESC: MEMORYBUSFREQUENCYLIMIT
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_MEMORYBUSFREQUENCYLIMIT                            0x34970A3C  // uint32

/// @DESC: POWERDOWNMODE
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Rang
  #define APCB_TOKEN_UID_POWERDOWNMODE                                      0x23DD2705  // uint32

/// @DESC: CBS_CMN_CLDOVDD_PVOLTAGE
/// @RANGE: 0x000002BC~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_CBS_CMN_CLDOVDD_PVOLTAGE                           0x7915D708  //uint32

/// @DESC: MEM_MBIST_AGGR_STATIC_LANE_SEL_L32
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL_L32                 0x745218AD  //uint32

/// @DESC: MEM_MBIST_AGGR_STATIC_LANE_SEL_U32
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL_U32                 0xFAC9F48F  //uint32

/// @DESC: MEM_MBIST_TGT_STATIC_LANE_SEL_L32
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL_L32                  0x81880D15  //uint32

/// @DESC: MEM_MBIST_TGT_STATIC_LANE_SEL_U32
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL_U32                  0xAF669F33  //uint32

/// @DESC: PCIE_RESET_GPIO_PIN_SELECT
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_PCIE_RESET_GPIO_PIN_SELECT                         0x596663AC  //uint32

/// @DESC: AP base address when fetch from SPI ROM
/// @RANGE: Lowest Available Memory~Top Of Memory = UITN32 Valid Range, must be 0x10000 aligned
  #define APCB_TOKEN_UID_CPU_FETCH_FROM_SPI_AP_BASE                         0xD403EA0E  // uint32

/// @DESC: Signature for CBS to keep the hash value
/// @RANGE: 0x00000000~0xFFFFFFFF = UITN32 Valid Range
  #define APCB_TOKEN_UID_CBS_SYNC_SIGNATURE                                 0xB331378E  // uint32


#endif // _APCB_V3_TOKEN_UID_H_

